name: eggplant

services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-eggplant}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-eggplant}
      POSTGRES_DB: ${DB_NAME:-eggplant}
    volumes:
      - pgdata:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  pgdata:
