name: eggplant

services:
  postgres:
    image: postgres:17
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"
    environment:
      POSTGRES_USER: ${DB_USER:-eggplant}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-eggplant}
      POSTGRES_DB: ${DB_NAME:-eggplant}
    volumes:
      - pgdata:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit
    ports:
      - "${SMTP_PORT:-1025}:${SMTP_PORT:-1025}"
      - "8025:8025"

volumes:
  pgdata:
